### PR TITLE
Feat/update user

### LINKED ISSUE #119: Update user

### PR DESCRIPTION
**Pull request by vzart**

### CODE REVIEW

**Review by StarryFolf — APPROVED** [review]
LGTM

**Review by kaitoz11 — CHANGES_REQUESTED** [review]
Shouldn't there be a validator?

**Review by kaitoz11 — APPROVED** [review]
oopps...
this is a miss click

**Review by kaitoz11 — CHANGES_REQUESTED** [review]
[sad](https://github.com/ProFile-org/ProFile-BE/pull/120#pullrequestreview-1454488600)

**Review by kaitoz11 — APPROVED** [review]
LGTM

**Pull request merged**
